# Generated by Django 4.1.2 on 2022-11-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.TextField(max_length=32),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image_url',
            field=models.TextField(max_length=256),
        ),
    ]
