# Generated by Django 4.1.2 on 2022-11-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_watchlist_listings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.TextField(max_length=4),
        ),
    ]
