# Generated by Django 4.1.2 on 2022-12-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_listing_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='auction_ended',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
